package vn.locdt.jats.addon.entity.modeling.model;

import vn.locdt.jats.addon.entity.modeling.strategy.AutoGeneratedStrategy;
import vn.locdt.jats.addon.entity.modeling.system.mysql.MySQLDataTypeMapping;

/**
 * Created by locdt on 1/29/2018.
 */
public class Column extends Model {
    protected Table table;
    protected int dataTypeCode;
    protected String dataType;
    protected int size;
    protected boolean primaryKey;
    protected boolean autoIncrement;
    protected boolean generatedColumn;
    protected boolean nullable;
    protected AutoGeneratedStrategy generatedStrategy;

    public Column() {
        super();
    }

    public Column(String name) {
        super(name);
    }

    public Table getTable() {
        return table;
    }

    public void setTable(Table table) {
        this.table = table;
    }

    public int getDataTypeCode() {
        return dataTypeCode;
    }

    public void setDataTypeCode(int dataTypeCode) {
        this.dataTypeCode = dataTypeCode;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    public boolean isPrimaryKey() {
        return primaryKey;
    }

    public void setPrimaryKey(boolean primaryKey) {
        this.primaryKey = primaryKey;
    }

    public boolean isAutoIncrement() {
        return autoIncrement;
    }

    public void setAutoIncrement(boolean autoIncrement) {
        this.autoIncrement = autoIncrement;
    }

    public boolean isNullable() {
        return nullable;
    }

    public void setNullable(boolean nullable) {
        this.nullable = nullable;
    }

    public boolean isGeneratedColumn() {
        return generatedColumn;
    }

    public void setGeneratedColumn(boolean generatedColumn) {
        this.generatedColumn = generatedColumn;
    }

    public String getJavaType() { return MySQLDataTypeMapping.getJavaType(dataTypeCode);}

    public AutoGeneratedStrategy getGeneratedStrategy() {
        return generatedStrategy;
    }

    public void setGeneratedStrategy(AutoGeneratedStrategy generatedStrategy) {
        this.generatedStrategy = generatedStrategy;
    }

    @Override
    public String toString() {
        return "Column{" +
                "name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", dataTypeCode=" + dataTypeCode +
                ", dataType='" + dataType + '\'' +
                ", size=" + size +
                ", primaryKey=" + primaryKey +
                ", autoIncrement=" + autoIncrement +
                ", generatedColumn=" + generatedColumn +
                ", nullable=" + nullable +
                ", generatedStrategy=" + generatedStrategy +
                '}';
    }
}
